---
title: "Instructores"
output:
  html_document:
    df_print: paged
---

**Jose Pablo Gomez-Vazquez**, MVZ, MPVM, PhD. Pablo es un investigador postdoctoral interesado en la modelación espacio-temporal para la prevención y control de enfermedades infecciosas. Obtuvo su licenciatura en la UANL, posteriormente realizó su maestría (Master in preventive veterinary medicine) en UC Davis y después el doctorado en Epidemiología también el UC Davis. Pablo se especializa en la aplicación de metodologías para el análisis y la modelación de sistemas complejos (p.ej. Análisis de redes sociales y modelos basados en agentes). Pablo ha trabajado con diferentes instituciones en Latinoamérica y África para la modelación de enfermedades emergentes y transfronterizas. Una de las principales motivaciones para pablo es el desarrollo de herramientas de libre acceso que se puedan aplicar para soportar la toma de decisiones y faciliten la comunicación de riesgo.  
 website: http://www.spablo-temporal.network


**Alejandro Zaldivar Gomez**, MVZ, MCS. Alejandro es un estudiante doctoral en la FMVZ-UNAM interesado en la aplicación de modelos matemáticos, la epidemiología espacial y el análisis de riesgo. Estudio la licenciatura en la FMVZ-UAEMex y además obtuvo una especialidad en Sistemas de Información Geográficos en la Facultad de Geografía de la UAEMex; posteriormente realizó su maestría (Maestria en Ciencias de la Salud) en la Escuela Superior de Medicina del IPN. Alejandro también ha laborado en México como analista en el área de diagnóstico de enfermedades infecciosas y en los programas federales de prevención y control de enfermedades en salud animal. Mi proyecto de tesis tiene por objetivo la aplicación de modelos epidemiológicos en enfermedades transfronterizas de interés veterinario, así como evaluar alternativas de planes de emergencia y atención de brotes. Alejandro busca desarrollar nuevas herramientas de análisis aplicados a la vigilancia epidemiológica y el fortalecimiento de los programas preventivos de enfermedades infecciosas.